#!/usr/bin/env node
var write    = require('fs').writeFileSync
  , exists   = require('fs').existsSync
  , basename = require('path').basename
  , relative = require('path').relative
  , extname  = require('path').extname
  , resolve  = require('path').resolve
  , glob     = require('glob').sync
  , utilise  = require('utilise')
  , beautify = require('js-beautify').js_beautify

var root = resolve(process.cwd(), process.argv[2] || 'dist/resources')
  , resources = beautify(str(glob(root+'/**/!(test|index).{js,css}')
      .map(resource)
      .reduce(to.obj('name'), {})))
      .replace(/"require\((.*?)\)"/g, 'require($1)')

write(resolve(root, 'index.js'), 'module.exports = ' + resources)

function resource(path) {
  var last = basename(path)
    , extn = extname(path)
    , name 
    , body
    , head 
    , res
    , obj

  if (extn == '.js') {
    name = last.replace('.js', '')
    body = 'require(\'./'+rel(path)+'\').default || require(\'./'+rel(path)+'\')'
    obj = require(path).default || require(path)
    res = is.obj(obj)                         ? body
        : exists(path.replace('.js', '.css')) ? { name: name, body: body, headers: { needs: '[css]' } } 
                                              : { name: name, body: body }
  }

  if (extn == '.css') {
    name = last
    body = file(path)
    res = { name: name, body: body }
  }

  return res
}

function rel(path) {
  return relative(root, path)
    .replace(/\\/g, '\/')
}